### ISSUE TITLE
The type initializer for 'Nested' threw an exception.

### ISSUE THREAD

**Issue by kishyr** [firmamentte/TriviaGameWebAPI#1]
Hi,

I've forked your repo (https://github.com/kishyr/TriviaGameWebAPI) and added support to get it to run in a Docker container. However, when I try to hit the GetGenres endpoint, the following error is returned: 

*Request*
```
GET /api/TriviaGame/V1/GetGenres HTTP/1.1
Host: localhost:8080
Connection: close
User-Agent: Paw/3.1.10 (Macintosh; OS X/10.15.2) GCDHTTPRequest
```

*Response*
```
HTTP/1.1 500 Internal Server Error
Connection: close
Date: Wed, 05 Feb 2020 19:30:13 GMT
Content-Type: text/plain
Server: Kestrel
Transfer-Encoding: chunked

The type initializer for 'Nested' threw an exception.
```

And this shows up in the API logs:
```
web_1  | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
web_1  |       Request starting HTTP/1.1 GET http://localhost:8080/api/TriviaGame/V1/GetGenres
web_1  | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
web_1  |       Route matched with {action = "GetGenres", controller = "TriviaGame"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.ActionResult`1[System.Collections.Generic.IEnumerable`1[TriviaGameWebAPI.BLL.DataContract.GenreResp]] GetGenres() on controller TriviaGameWebAPI.Controllers.TriviaGameController (TriviaGameWebAPI).
web_1  | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
web_1  |       Executing action method TriviaGameWebAPI.Controllers.TriviaGameController.GetGenres (TriviaGameWebAPI) - Validation state: Valid
web_1  | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
web_1  |       Executed action TriviaGameWebAPI.Controllers.TriviaGameController.GetGenres (TriviaGameWebAPI) in 1.0014ms
web_1  | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
web_1  |       Request finished in 1.4526ms 500 text/plain
```

Any advice on how to fix this?

**Comment by firmamentte** [comment]
Hi,

"ConnectionStrings": {
    "DatabasePath": "Server=.\\SQLEXPRESS;Database=TriviaGameDB;Integrated Security=True"
  },

In the appsettings.json file, you will see the above.

Please change the ".\\SQLEXPRESS" Server to the one running on your machine. e.g ".\\MYSQLEXPRESS"

Please make sure the Database is TriviaGameDB.

**Comment by firmamentte** [comment]
Hi,

I have posted a comment on github.

Thanks.

**Comment by kishyr** [comment]
@firmamentte In my docker instance, the hostname of the container hosting the SQL Server Express database is named "db", so I changed the `appsettings.json` file to read:

```
"ConnectionStrings": {
"DatabasePath": "Server=.\db;Database=TriviaGameDB;Integrated Security=True"
},
```

The .net core app starts fine with the above config, and when the `Server=` string was set to something else (eg. `localhost`), the .net core app did not start and threw an error, so I think it is starting up okay. Could be wrong though.

**Comment by firmamentte** [comment]
@kishyr Can you try this.

In **TriviaGameWebAPI.Core** >> **Mappings folder**, right click the **mapping files** and make sure the Build Action Property is **Embedded resource**

**Comment by firmamentte** [comment]
@kishyr Can you try this.

In **TriviaGameWebAPI.Core** >> **Domain** >> **Mappings**, right click the **.hbm.xml** files and make sure the Build Action Property is Embedded resource

**Comment by firmamentte** [comment]
@kishyr 

From Thursday to Current, I have been experiencing too much power cut and bad network connection in my location.

I was just wondering if you are able to connect the API to the DB.

There problem there is the connection to the DB. 

If the host name of your Container is "db" then maybe you should try the following:

`"ConnectionStrings": {
"DatabasePath": "Server=.\SQLServerExpressInstance;Database=TriviaGameDB;Integrated Security=True"
},`

or

`"ConnectionStrings": {
"DatabasePath": "Server=db\SQLServerExpressInstance;Database=TriviaGameDB;Integrated Security=True"
},`

Your SQL Server Express Instance should be different from your Container Hostname

I have attach a picture of how your SQL Server Express Instance should look like.

I Look forward to hearing from you.

![pic](https://user-images.githubusercontent.com/58068861/74083490-5a97a600-4a6d-11ea-81c4-ad3d6c242ba5.png)

**Comment by kishyr** [comment]
Thanks for helping to troubleshoot. Because I'm running everything from a Docker container, I don't have a GUI (or even Windows/IIS itself) to configure. I'll google what the equivalent steps would be.

**Comment by kishyr** [comment]
Hi @firmamentte, I think I got the two containers (API & DB) talking to each other in Docker. 

How when I use the CreateGame endpoint, I get this error response:

```json
{
  "": [
    "Unexpected character encountered while parsing value: {. Path '', line 1, position 1."
  ]
}
```

This is my request:

```
POST /api/TriviaGame/V1/CreateGame HTTP/1.1
Content-Type: application/json; charset=utf-8
Host: localhost:8080
Connection: close
User-Agent: Paw/3.1.10 (Macintosh; OS X/10.15.2) GCDHTTPRequest
Content-Length: 22

{"GenreName":"Horror"}
```

Any idea on how to debug this? If you're available on Skype, we can debug it in real-time.

**Comment by firmamentte** [comment]
Hi @kishyr,

Good to hear from you.

Can you please make sure that you enter Horror in double quotes("") in the Request Body.

Thanks

![triviaGame](https://user-images.githubusercontent.com/58068861/74654329-c0351200-5192-11ea-9593-185e885588b7.png)

**Comment by kishyr** [comment]
Thanks for everything. I've managed to get your project up and running and was able to run through all your API endpoints.
